-- Update goal creation trigger to create two default notes
-- Add Atman chat tables
-- Add device tokens for push notifications

-- =====================
-- ATMAN CHAT TABLES
-- =====================

-- Chat messages for Atman conversations
create table chat_messages (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

-- AI suggestions generated by Atman
create table ai_suggestions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  chat_message_id uuid references chat_messages(id) on delete cascade not null,
  suggestion_type text not null check (suggestion_type in ('note', 'action', 'principle', 'goal')),
  suggestion_data jsonb not null, -- Contains the full data for the suggested item
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'modified')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS for chat_messages
alter table chat_messages enable row level security;

create policy "Users can view own chat messages" on chat_messages for select using (auth.uid() = user_id);
create policy "Users can create own chat messages" on chat_messages for insert with check (auth.uid() = user_id);
create policy "Users can delete own chat messages" on chat_messages for delete using (auth.uid() = user_id);

-- RLS for ai_suggestions
alter table ai_suggestions enable row level security;

create policy "Users can view own suggestions" on ai_suggestions for select using (auth.uid() = user_id);
create policy "Users can create own suggestions" on ai_suggestions for insert with check (auth.uid() = user_id);
create policy "Users can update own suggestions" on ai_suggestions for update using (auth.uid() = user_id);
create policy "Users can delete own suggestions" on ai_suggestions for delete using (auth.uid() = user_id);

-- Indexes for Atman tables
create index idx_chat_messages_user_id on chat_messages(user_id);
create index idx_chat_messages_created_at on chat_messages(created_at);
create index idx_ai_suggestions_user_id on ai_suggestions(user_id);
create index idx_ai_suggestions_chat_message_id on ai_suggestions(chat_message_id);
create index idx_ai_suggestions_status on ai_suggestions(status);

-- =====================
-- DEVICE TOKENS FOR PUSH NOTIFICATIONS
-- =====================

create table device_tokens (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  token text not null,
  platform text not null check (platform in ('android', 'ios', 'web')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, token)
);

-- RLS for device_tokens
alter table device_tokens enable row level security;

create policy "Users can view own device tokens" on device_tokens for select using (auth.uid() = user_id);
create policy "Users can create own device tokens" on device_tokens for insert with check (auth.uid() = user_id);
create policy "Users can update own device tokens" on device_tokens for update using (auth.uid() = user_id);
create policy "Users can delete own device tokens" on device_tokens for delete using (auth.uid() = user_id);

-- Index for device_tokens
create index idx_device_tokens_user_id on device_tokens(user_id);

-- =====================
-- UPDATE GOAL CREATION TRIGGER
-- =====================

create or replace function handle_goal_creation()
returns trigger as $$
declare
  new_folder_id uuid;
  new_notebook_id uuid;
begin
  -- Create folder for goal
  insert into folders (user_id, name, goal_id)
  values (new.user_id, new.what_do_you_want, new.id)
  returning id into new_folder_id;

  -- Create notebook for goal
  insert into notebooks (user_id, name, goal_id)
  values (new.user_id, new.what_do_you_want, new.id)
  returning id into new_notebook_id;

  -- Update goal with folder and notebook ids
  update goals
  set folder_id = new_folder_id, notebook_id = new_notebook_id
  where id = new.id;

  -- Create first note: "What do you want?"
  insert into notes (user_id, notebook_id, title, content)
  values (
    new.user_id,
    new_notebook_id,
    'What do you want?',
    '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Describe what you want to achieve with this goal..."}]}]}'::jsonb
  );

  -- Create second note: "How will you achieve [goal] in light of what is true?"
  insert into notes (user_id, notebook_id, title, content)
  values (
    new.user_id,
    new_notebook_id,
    'How will you achieve ' || new.what_do_you_want || ' in light of what is true?',
    '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Outline your strategy and approach..."}]}]}'::jsonb
  );

  return new;
end;
$$ language plpgsql security definer;
